# 这个里面定义的东西都是全局变量，可以直接在模板里面调用
# site.title来访问   site代表整个站点  以及data文件夹的数据文件（这里没有）
# page这种表示当前页面
# Setup
title:        RTTL-VC Samples
# tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Heixiaoniu
  # url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown